- name: "Abort if user did not specify user_var_install_devices"
  fail:
    msg: "user_var_install_devices list var must be set (see group_vars/all file)"
  when: user_var_install_devices is not defined

