- name: "Import variables from optional, user-specified file"
  include_vars:
    file: "{{ user_vars_file }}"
  when: user_vars_file is defined
  ignore_errors: true

- name: "Abort if user did not specify user_var_device_1"
  fail:
    msg: "user_var_device_1 variable must be set to 'sdx' (see group_vars/all file)"
  when: user_var_device_1 is not regex("^sd.$")

