- hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: "install_drive"
      prompt: "Enter Installation Drive (e.g. sda)"
      default: "sda"
      private: no
  tasks:
  - name: Install htop
    pacman:
      name: htop
      state: present

