- hosts: localhost
  become: true
  connection: local
  vars_prompt:
    - name: install_drive
      prompt: "Enter Installation Drive (e.g. sda)"
      private: no
  tasks:
    - name: "Install htop"
      pacman:
        name: htop
        state: present
    - name: "Add GPT boot partition"
      parted:
        device: /dev/{{ install_drive }}
        label: gpt
        number: 1
        part_start: 0%
        part_end: 2MB
        part_type: primary
        flags: [ bios_grub ]
        state: present

