- hosts: localhost
  become: true
  connection: local
  vars_prompt:
    - name: install_drive
      prompt: "Enter Installation Drive (e.g. sda)"
      private: no
  tasks:
    - name: "Install htop"
      pacman:
        name: htop
        state: present
    - name: "Partition single drive"
      parted:
        device: /dev/{{ install_drive }}
        label: gpt

