- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install htop
    pacman:
      name: htop
      state: present
  - debug: msg="{{ hostvars[inventory_hostname]["ansible_devices"] | select('match', '^sd.?$') | list }}"

