- hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: install_drive
      private: no
  tasks:
  - name: Install htop
    pacman:
      name: htop
      state: present
  - debug: msg={{ install_drive }}

