- hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: install_drive
      prompt: "Enter Installation Drive (e.g. sda)"
      default: "sda"
      private: yes
  tasks:
  - name: Install htop
    pacman:
      name: htop
      state: present
  - debug: msg={{ install_drive }}

