- hosts: localhost
  become: true
  connection: local
  vars_prompt:
    - name: disk_format_install_drive
      prompt: "Enter Installation Drive (e.g. sda)"
      private: no
  roles:
    - disk-format
    - pool-creation

