- hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: "Import variables from optional, user-specified file"
      include_vars:
        file: "{{ user_vars_file }}"
      when: user_vars_file is defined
      ignore_errors: true
    - name: "Abort if user did not specify user_var_motherboard_type"
      fail:
        msg: "user_var_motherboard_type variable must be specified (see group_vars/all file)"
      when: user_var_motherboard_type != "bios" and user_var_motherboard_type != "uefi"
    - name: "Abort if user did not specify user_var_device_1"
      fail:
        msg: "user_var_device_1 variable must be set to \"sdx\" (see group_vars/all file)"
      when: user_var_device_1 is not regex("^sd.$")
  tasks:
    - include_role:
        name: disk-format
      vars:
        disk_format_def_motherboard_type: "{{ user_var_motherboard_type }}"
        disk_format_def_device_1: "{{ user_var_device_1 }}"
        disk_format_def_device_2: "{{ user_var_device_2 }}"
        disk_format_var_boot_partition_label: "{{ const_var_boot_partition_label }}"
        disk_format_var_zfs_partition_label: "{{ const_var_zfs_partition_label }}"
    - include_role:
        name: pool-creation

