- hosts: localhost
  become: true
  connection: local
  vars_prompt:
    - name: install_drive
      prompt: "Enter Installation Drive (e.g. sda)"
      private: no
  tasks:
    - name: "Install htop"
      pacman:
        name: htop
        state: present
    - name: "Add boot partition"
      parted:
        device: /dev/{{ install_drive }}
        label: gpt
        number: 1
        part_start: 0%
        part_end: 2MB
        name: "boot_partition"
        flags: [ bios_grub ]
        state: present
    - name: "Add zfs partition"
      parted:
        device: /dev/{{ install_drive }}
        label: gpt
        number: 2
        part_start: 2MB
        part_end: 100%
        name: "zfs_partition"
        flags: [ boot ]
        state: present

