- hosts: localhost
  become: true
  connection: local
  vars_prompt:
    - name: disk_format_install_drive
      prompt: "Enter Installation Drive (e.g. sda)"
      private: no
  pre_tasks:
    - name: "Abort if user did not specify install_disk_device_1"
      fail:
        msg: "install_disk_device_1 must be specified (see group_vars/all)"
      when: install_disk_device_1 == "none"
  roles:
    - disk-format
    - pool-creation

