- hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: "Import user-vars file (as req), and check all user-vars defined"
      include_role:
        name: user-vars-chk
    - name: "Compose partition-label strings for the installation disk(s)"
      set_fact:
        play_fact_device_1_boot_partlabel: "{{ const_var_boot_partlabel_base }}{{ mirror0_append }}"
        play_fact_device_1_zfs_partlabel: "{{ const_var_zfs_partlabel_base }}{{ mirror0_append }}"
        play_fact_device_2_boot_partlabel: "{{ device_2_boot_base }}{{ mirror1_append }}"
        play_fact_device_2_zfs_partlabel: "{{ device_2_zfs_base }}{{ mirror1_append }}"
  tasks:
    - include_role:
        name: disk-format
      vars:
        disk_format_def_motherboard_type: "{{ user_var_motherboard_type }}"
        disk_format_def_device_1: "{{ user_var_device_1 }}"
        disk_format_def_device_2: "{{ user_var_device_2 }}"
        disk_format_def_device_1_boot_partlabel: "{{ play_fact_device_1_boot_partlabel }}"
        disk_format_def_device_1_zfs_partlabel: "{{ play_fact_device_1_zfs_partlabel }}"
        disk_format_def_device_2_boot_partlabel: "{{ play_fact_device_2_boot_partlabel }}"
        disk_format_def_device_2_zfs_partlabel: "{{ play_fact_device_2_zfs_partlabel }}"
    - include_role:
        name: pool-creation
      vars:
        pool_creation_def_device_1_zfs_partlabel: "{{ play_fact_device_1_zfs_partlabel }}"
        pool_creation_def_device_2_zfs_partlabel: "{{ play_fact_device_2_zfs_partlabel }}"
        pool_creation_def_zpool_name: "{{ const_var_zpool_name }}"
    - include_role:
        name: dataset-creation
      vars:
        dataset_creation_def_zpool_name: "{{ const_var_zpool_name }}"
    - include_role:
        name: zroot-config
      vars:
        zroot_cofig_def_zpool_name: "{{ const_var_zpool_name }}"

