- hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: "Ensure system clock is accurate"
      service:
        name: timedatectl
        args: set-ntp
        state: started
  tasks:
    - name: "Install the basic, minimal, zfs-based Arch Linux to the drive(s)"
      include_role:
        name: "{{ item }}"
      loop:
        - user-vars-chk
        - play-fact-set
        - disk-format
        - pool-creation
        - dataset-creation
        - zroot-config
      vars:
        disk_format_def_motherboard_type: "{{ play_fact_motherboard_type }}"
        disk_format_def_device_1: "{{ user_var_install_devices[0] }}"
        disk_format_def_device_2: "{{ 'none' if user_var_install_devices|length == 1 else user_var_install_devices[1] }}"
        disk_format_def_device_1_boot_partlabel: "{{ play_fact_device_1_boot_partlabel }}"
        disk_format_def_device_1_zfs_partlabel: "{{ play_fact_device_1_zfs_partlabel }}"
        disk_format_def_device_2_boot_partlabel: "{{ play_fact_device_2_boot_partlabel }}"
        disk_format_def_device_2_zfs_partlabel: "{{ play_fact_device_2_zfs_partlabel }}"
        pool_creation_def_device_1_zfs_partlabel: "{{ play_fact_device_1_zfs_partlabel }}"
        pool_creation_def_device_2_zfs_partlabel: "{{ play_fact_device_2_zfs_partlabel }}"
        pool_creation_def_zpool_name: "{{ user_var_zpool_name }}"
        dataset_creation_def_zpool_name: "{{ user_var_zpool_name }}"
        zroot_config_def_zpool_name: "{{ user_var_zpool_name }}"

