- hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: "Import variables from optional, user-specified file"
      include_vars:
        file: "{{ user_vars_file }}"
        when: user_vars_file is defined
        ignore_errors: true
    - name: "Abort if user did not specify install_disk_device_1"
      assert:
        that:
          - install_disk_device_1 != "none"
        msg: "install_disk_device_1 must be specified (see group_vars/all file)"
        quiet: true
  roles:
    - disk-format
    - pool-creation

