- hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: "Import variables from optional, user-specified file"
      include_vars:
        file: "{{ user_vars_file }}"
      when: user_vars_file is defined
      ignore_errors: true
    - name: "Abort if user did not specify user_var_motherboard_type"
      fail:
        msg: "user_var_motherboard_type variable must be specified (see group_vars/all file)"
      when: user_var_motherboard_type != "bios" and user_var_motherboard_type != "uefi"
    - name: "Abort if user did not specify user_var_device_1"
      fail:
        msg: "user_var_device_1 variable must be set to 'sdx' (see group_vars/all file)"
      when: user_var_device_1 is not regex("^sd.$")
    - name: "Compose 'mirror' string-appends if installing to mirrored disks"
      set_fact:
        mirror0_append: "_mirror0"
        mirror1_append: "_mirror1"
      when: user_var_device_2 is regex("^sd.$")
    - name: "Compose partition-label strings for the installation disk(s)"
      set_fact:
        play_fact_device_1_boot_partlabel: "{{ const_var_boot_partlabel_base}}{{ mirror0_append | default(omit) }}"
        play_fact_device_1_zfs_partlabel: "{{ const_var_zfs_partlabel_base}}{{ mirror0_append | default(omit) }}"
        play_fact_device_2_boot_partlabel: "{{ const_var_boot_partlabel_base}}{{ mirror1_append | default(omit) }}"
        play_fact_device_2_zfs_partlabel: "{{ const_var_zfs_partlabel_base}}{{ mirror1_append | default(omit) }}"
  tasks:
    - include_role:
        name: disk-format
      vars:
        disk_format_def_motherboard_type: "{{ user_var_motherboard_type }}"
        disk_format_def_device_1: "{{ user_var_device_1 }}"
        disk_format_def_device_2: "{{ user_var_device_2 }}"
        disk_format_def_device_1_boot_partlabel: "{{ play_fact_device_1_boot_partlabel }}"
        disk_format_def_device_1_zfs_partlabel: "{{ play_fact_device_1_zfs_partlabel }}"
        disk_format_def_device_2_boot_partlabel: "{{ play_fact_device_2_boot_partlabel }}"
        disk_format_def_device_2_zfs_partlabel: "{{ play_fact_device_2_zfs_partlabel }}"
    - include_role:
        name: pool-creation

