- name: "For BIOS motherboard: format disk with boot and zfs partitions"
  include_tasks: format_disk.yml
  vars:
    disk_device: "{{ single_device }}"
    boot_partition_size: "{{ disk_format_var_bios_boot_partition_size }}"
    boot_partition_code: "{{ disk_format_var_gdisk_part_code_bios_boot }}"
  when: disk_format_def_motherboard_type == "bios"

- name: "For UEFI motherboard: format disk with boot and zfs partitions"
  include_tasks: format_disk.yml
  vars:
    disk_device: "{{ single_device }}"
    boot_partition_size: "{{ disk_format_var_uefi_boot_partition_size }}"
    boot_partition_code: "{{ disk_format_var_gdisk_part_code_uefi_boot }}"
  when: disk_format_def_motherboard_type == "uefi"

