- name: "Install gptfdisk package"
  pacman:
    name: gptfdisk
    state: present

- name: For BIOS motherboard: format first disk with boot and zfs partitions
  include_tasks: format_disk.yml
  vars:
    disk_device: "{{ disk_format_def_device_1 }}"
    boot_partition_size: "{{ disk_format_var_bios_boot_partition_size }}"
    boot_partition_code: "{{ disk_format_var_gdisk_part_code_bios_boot }}"
  when: disk_format_motherboard_type == "bios"

