- name: "Install gptfdisk package"
  pacman:
    name: gptfdisk
    state: present

- name: "Erase disk, including part-table and partitions"
  command: sgdisk --zap-all /dev/{{ install_disk_device_1|quote }}

- name: "Write new GPT partition table to disk"
  command: sgdisk --mbrtogpt /dev/{{ install_disk_device_1|quote }}

- name: "Add BIOS-motherboard GRUB bootloader partition to disk"
  command: sgdisk --new 1:0:{{ disk_format_bios_boot_partition_size|quote }}
                  --typecode 1:{{ disk_format_gdisk_part_code_bios_boot|quote }}
                  --change-name 1:{{ gvar_boot_partition_label|quote }}
                  /dev/{{ install_disk_device_1|quote }}

- name: "Add zfs partition to disk"
  command: sgdisk --new 2:0:0
                  --typecode 2:{{ disk_format_gdisk_part_code_solaris_root|quote }}
                  --change-name 2:{{ gvar_zfs_partition_label|quote }}
                  /dev/{{ install_disk_device_1|quote }}

