- name: "Install gptfdisk package"
  pacman:
    name: gptfdisk
    state: present

- name: Format first disk with boot and zfs partitions
  include_task: format_single_disk.yml
  vars:
    disk_device: "{{ disk_format_def_device_1 }}"

