- name: "Install gptfdisk package"
  pacman:
    name: gptfdisk
    state: present

- name: "Format first disk"
  include_tasks: format_single.yml
  vars:
    single_device: "{{ disk_format_def_device_1 }}"
    boot_partition_label: "{{ disk_format_def_device_1_boot_partlabel }}"
    zfs_partition_label: "{{ disk_format_def_device_1_zfs_partlabel }}"

- name: "Format second disk (for mirrored install) if selected"
  include_tasks: format_single.yml
  vars:
    single_device: "{{ disk_format_def_device_2 }}"
    boot_partition_label: "{{ disk_format_def_device_2_boot_partlabel }}"
    zfs_partition_label: "{{ disk_format_def_device_2_zfs_partlabel }}"
  when: disk_format_def_device_2 is regex("^sd.$")

