- name: "Install gptfdisk package"
  pacman:
    name: gptfdisk
    state: present

- name: "Format first disk"
  include_tasks: format_single.yml
  vars:
    single_device: "{{ disk_format_def_device_1 }}"

- name: "Format second disk (for mirrored install) if selected"
  include_tasks: format_single.yml
  vars:
    single_device: "{{ disk_format_def_device_2 }}"
  when: disk_format_def_device_2 is regex("^sd.$")

