- name: "Unmount all zfs filesystems"
  command: zfs unmount -a

- name: "Set bootfs property on default-boot-environment root filesystem"
  command: zpool set bootfs={{ zroot_config_def_zpool_name }}/ROOT/default {{ zroot_config_def_zpool_name|quote }}

- name: "Export the new zpool"
  command: zpool export {{ zroot_config_def_zpool_name|quote }}

- name: "Re-import the new zpool"
  command: zpool import -d /dev/disk/by-partlabel -R /mnt {{ zroot_config_def_zpool_name|quote }}

- name: "Create 'zpool.cache' as required, and copy to zpool filesystem"
  block:
    - name: "Create 'zpool.cache' source and destination dirs, if they don't exist"
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ src_dir }}"
        - "{{ dest_dir }}"
    - name: "Create 'zpool.cache' file if it does not exist"
      command:
        cmd: zpool set cachefile={{ src_file|quote }} {{ zroot_config_def_zpool_name|quote }}
        creates: "{{ src_file }}"
    - name: "Copy 'zpool.cache' file into the zpool filesystem"
      copy:
        src: "{{ src_file }}"
        dest: "{{ dest_file }}"
        force: yes
  vars:
    cache_file: "zpool.cache"
    src_dir: "/etc/zfs"
    src_file: "/etc/zfs{{ cache_file }}"
    dest_dir: "/mnt/etc/zfs"
    dest_file: "/mnt/etc/zfs{{ cache_file }}"

