- name: "Unmount all zfs filesystems"
  command: zfs unmount -a

- name: "Set bootfs property on default-boot-environment root filesystem"
  command: zpool set bootfs={{ zroot_config_def_zpool_name }}/ROOT/default {{ zroot_config_def_zpool_name|quote }}

- name: "Export the new zpool"
  command: zpool export {{ zroot_config_def_zpool_name|quote }}

- name: "Re-import the new zpool"
  command: zpool import -d /dev/disk/by-partlabel -R /mnt {{ zroot_config_def_zpool_name|quote }}

- name: "Create zpool.cache file if it does not exist"
  command: zpool set cachefile=/etc/zfs/zpool.cache {{ zroot_config_def_zpool_name|quote }}
  creates: "/etc/zfs/zpool.cache"

- name: "Copy zpool.cache file into the zpool filesystem"
  copy:
    src: "/etc/zfs/zpool.cache"
    dest: "/mnt/etc/zfs/zpool.cache"
    force: yes

