- name: "Start systemd-timesyncd to ensure system clock is accurate"
  service:
    name: systemd-timesyncd
    state: started

- name: "Sync pacman package database"
  pacman:
    update_cache: yes
    update_cache_extra_args: "--noconfirm"

- name: "Update mirror-server-list on the archiso live USB with fastest servers"
  block:
    - name: "Install reflector package"
      pacman:
        name: reflector
        state: present
    - name: "Check if the mirror-server-list backup copy already exists"
      stat:
        path: "{{ mirror_list_bkup }}"
      register: bkup_file
    - name: "Create backup copy of mirror-list, if it does not exist"
      copy:
        src: "{{ mirror_list }}"
        dest: "{{ mirror_list_bkup }}"
      when: bkup_file.stat.exists == false
    - name: "Find fastest servers, and replace the current archiso mirror-list"
      command: reflector --country 'United States'
                         --latest '200'
                         --protocol 'http'
                         --protocol 'https'
                         --sort 'rate'
                         --save {{ mirror_list|quote }}
      when: bkup_file.stat.exists == false
  vars:
    mirror_list: "/etc/pacman.d/mirrorlist"
    mirror_list_bkup: "{{ mirror_list }}_bkup"

- name: "Remove all subdirs/files from '/mnt', which will be used for chroot"
  block:
    - name: "Create list of all subdirs/files in '/mnt'"
      find:
        path: "/mnt"
        file_type: any
      register: mnt_content
    - name: "Remove all subdirs/files in '/mnt'"
      file:
        path: "{{ item_main.path }}"
        state: absent
      loop: "{{ mnt_content.files }}"
      loop_control:
        loop_var: item_main

