- name: "Start systemd-timesyncd to ensure system clock is accurate"
  service:
    name: systemd-timesyncd
    state: started

- name: "Sync pacman package database"
  pacman:
    update_cache: yes
    update_cache_extra_args: "--noconfirm"

- name: "Update mirror-server-list on the archiso live USB with fastest servers"
  block:
    - name: "Install reflector package"
      pacman:
        name: reflector
        state: present
    - name: "Check if the mirror-server-list backup copy already exists"
      stat:
        path: "{{ mirror_list_bkup }}"
      register: bkup_file
    - name: "Create backup copy of mirror-list, if it does not exist"
      copy:
        src: "{{ mirror_list }}"
        dest: "{{ mirror_list_bkup }}"
      when: bkup_file.stat.exists == false
    - name: "Find fastest servers, and replace the current archiso mirror-list"
      command: reflector --country 'United States'
                         --latest '200'
                         --protocol 'http'
                         --protocol 'https'
                         --sort 'rate'
                         --save {{ mirror_list|quote }}
      when: bkup_file.stat.exists == false
  vars:
    mirror_list: "/etc/pacman.d/mirrorlist"
    mirror_list_bkup: "{{ mirror_list }}_bkup"

- name: "Load the zfs kernel module"
  modprobe:
    name: zfs
    state: present

- name: "Unmount EFI boot partition from '[chroot]/efi', if it is mounted"
  mount:
    path: "{{ archiso_config_def_efi_chroot_dir }}"
    state: unmounted

