- name: "Wipe disk partition table, partitions, and filesystem metadata"
  command: wipefs --all --force /dev/{{ device }}
  loop: "{{ archiso_config_def_install_devices }}"
  loop_control:
    loop_var: device
