- name: "Write GRUB bootloader code to BIOS partition"
  command: grub-install --boot-directory="{{ grub_install_def_arch_chroot_dir }}/boot"
                        /dev/{{ device }}
  loop: "{{ grub_install_def_install_devices }}"
  loop_control:
    loop_var: device
  environment:
    ZPOOL_VDEV_NAME_PATH: 1

