- name: "Install 'efibootmgr' package to chroot"
  command: arch-chroot {{ grub_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -S efibootmgr

- name: "Write GRUB bootloader code to first disk EFI partition"
  include_tasks: uefi_part.yml
  vars:
    boot_partlabel: "{{ grub_install_def_device_1_boot_partlabel }}"

- name: "Write GRUB bootloader code to second disk EFI partition, if exists"
  include_tasks: uefi_part.yml
  vars:
    boot_partlabel: "{{ grub_install_def_device_2_boot_partlabel }}"
  when: grub_install_def_device_2_boot_partlabel != ""

- name: "Copy GRUB unicode font from /usr/share to /boot/grub"
  copy:
    src: "{{ grub_install_def_arch_chroot_dir }}/usr/share/grub/unicode.pf2"
    dest: "{{ grub_install_def_arch_chroot_dir }}/boot/grub/unicode.pf2"

