- name: "Install optional user-defined packages to live USB"
  command: arch-chroot {{ post_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -S {{ user_var_extra_packages | join(" ") }}
  when: user_var_extra_packages is defined

- name: "Clone optional user-defined repo and place in `/root`"
  git:
    repo: "{{ user_var_bootstrap_git_repo }}"
    dest: "{{ post_install_def_arch_chroot_dir }}/root/\
           {{ user_var_bootstrap_git_repo | urlsplit('path') | basename | splitext | first }}"
  when: user_var_bootstrap_git_repo is defined

- name: "Re-sync kernel-recognized disk partition(s)"
  command: partprobe

- name: "Unmount EFI boot partition from '[chroot]/efi', if it is mounted"
  mount:
    path: "{{ post_install_def_efi_chroot_dir }}"
    state: unmounted

- name: "Unmount all zfs filesystems"
  command: zfs unmount -a

- name: "Export the zpool"
  command: zpool export {{ post_install_def_zpool_name|quote }}

