- name: "Create the new zpool on the installation disk(s)"
  # -f: force creation, clobbering vdev metadata if it exists
  # -d: do not enable any features - specify features individually with -o
  # -m none: don't set persistent mountpoint for /[zpool_name] pool root dataset
  # -R [mount_dir]: mount zpool temporarily on [mount_dir], and don't use cachefile
  # -O compress=on: use default compression algorithm for all pool datasets
  command: zpool create -f -d
              -m none
              -R {{ pool_creation_def_arch_chroot_dir|quote }}
              -O compress=on
              -o ashift=12
              -o feature@allocation_classes=enabled
              -o feature@async_destroy=enabled
              -o feature@bookmarks=enabled
              -o feature@embedded_data=enabled
              -o feature@empty_bpobj=enabled
              -o feature@enabled_txg=enabled
              -o feature@extensible_dataset=enabled
              -o feature@filesystem_limits=enabled
              -o feature@hole_birth=enabled
              -o feature@large_blocks=enabled
              -o feature@lz4_compress=enabled
              -o feature@project_quota=enabled
              -o feature@resilver_defer=enabled
              -o feature@spacemap_histogram=enabled
              -o feature@spacemap_v2=enabled
              -o feature@userobj_accounting=enabled
              -o feature@zpool_checkpoint=enabled
              {{ pool_creation_def_zpool_name|quote }} {{ mirror_opt }} {{ device_1_part_path }} {{ device_2_part_path }}
  vars:
    device_1_part_path: "/dev/disk/by-partlabel/{{ pool_creation_def_device_1_zfs_partlabel }}"
    device_2_string: "/dev/disk/by-partlabel/{{ pool_creation_def_device_2_zfs_partlabel }}"
    device_2_part_path: "{{ '' if pool_creation_def_device_2_zfs_partlabel == '' else device_2_string }}"
    mirror_opt:  "{{ '' if pool_creation_def_device_2_zfs_partlabel == '' else 'mirror' }}"

