- name: "Create boot-environment datasets"
  block:
  - name: "Create boot-environment-parent dataset: [zpool_name]/ROOT"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/ROOT"
      extra_zfs_properties:
        canmount: "off"
        mountpoint: "none"
      state: present
  - name: "Create main boot environment dataset: [zpool_name]/ROOT/default"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/ROOT/default"
      extra_zfs_properties:
        mountpoint: "/"
      state: present

