- name: "Check that status of the new zpool is 'ONLINE'"
  command: zpool status -x {{ dataset_creation_def_zpool_name|quote }}
  register: cmd_result
  failed_when: "'is healthy' not in cmd_result.stdout"

- name: "Create [zpool_name]/ROOT dataset to hold boot environments"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/ROOT"
    extra_zfs_properties:
      canmount: "off"
      mountpoint: "none"
    state: present

- name: "Create main ROOT/default boot environment dataset"
  command: zfs create -o mountpoint=/
               {{ dataset_creation_def_zpool_name }}/ROOT/default
  register: cmd_result
  failed_when:
    - cmd_result.rc != 0
    - "'filesystem successfully created' not in cmd_result.stderr"

- name: "Create [zpool_name]/usr system dataset as part of boot environment"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/usr"
    extra_zfs_properties:
      canmount: "off"
      mountpoint: "/usr"
    state: present

