- name: "Check that status of the new zpool shows 'ONLINE'"
  command: zpool status -x {{ dataset_creation_def_zpool_name|quote }}
  register: cmd_result
  failed_when: "'is healthy' not in cmd_result.stdout"

- name: "Create boot-environment datasets"
  block:
  - name: "Create boot-environment-parent dataset: [zpool_name]/ROOT"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/ROOT"
      extra_zfs_properties:
        canmount: "off"
        mountpoint: "none"
      state: present
  - name: "Create main boot environment dataset: [zpool_name]/ROOT/default"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/ROOT/default"
      extra_zfs_properties:
        mountpoint: "/"
      state: present

- name: "Create /usr system datasets"
  block:
  - name: "Create [zpool_name]/usr (as part of boot environment)"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/usr"
      extra_zfs_properties:
        canmount: "off"
        mountpoint: "/usr"
      state: present
  - name: "Create [zpool_name]/usr/src"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/usr/src"
      extra_zfs_properties:
        mountpoint: "/usr/src"
      state: present
  - name: "Create [zpool_name]/usr/local"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/usr/local"
      extra_zfs_properties:
        mountpoint: "/usr/local"
      state: present

