- name: "Create [zpool_name]/usr system dataset (part of boot environment)"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/usr"
    extra_zfs_properties:
      canmount: "off"
      mountpoint: "/usr"
    state: present

- name: "Create /usr mountable, snapshottable stand-alone datasets"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/usr/{{ itemj.path }}"
    extra_zfs_properties:
      mountpoint: "/usr/{{ itemj.path }}"
    state: present
  loop:
    - path: "src"
    - path: "local"
  loop_control:
    loop_var: itemj

