- name: "Create /var system datasets that are part of boot environment"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/var{{ item_usr.path }}"
    extra_zfs_properties:
      canmount: "off"
      mountpoint: "/var{{ item_usr.path }}"
    state: present
  loop:
    - path: ""
    - path: "/lib"
    - path: "/lib/systemd"
  loop_control:
    loop_var: item_usr

- name: "Create /var mountable, snapshottable stand-alone datasets"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/var/{{ item_usr.path }}"
    extra_zfs_properties:
      mountpoint: "/var/{{ item_usr.path }}"
      acltype: "{{ item_usr.acl | default(omit) }}"
    state: present
  loop:
    - path: "cache"
    - path: "lib/lxc"
    - path: "lib/lxd"
    - path: "lib/machines"
    - path: "lib/libvirt"
    - path: "lib/systemd/coredump"
    - path: "log"
    - path: "log/journal"
      acl: "posixacl"
  loop_control:
    loop_var: item_usr

