- name: "Create /var system datasets that are part of boot environment"
  block:
  - name: "Create [zpool_name]/var"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/var"
      extra_zfs_properties:
        canmount: "off"
        mountpoint: "/var"
      state: present
  - name: "Create [zpool_name]/var/lib"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/var/lib"
      extra_zfs_properties:
        canmount: "off"
        mountpoint: "/var/lib"
      state: present
  - name: "Create [zpool_name]/var/lib/systemd"
    zfs:
      name: "{{ dataset_creation_def_zpool_name }}/var/lib/systemd"
      extra_zfs_properties:
        canmount: "off"
        mountpoint: "/var/lib/systemd"
      state: present

- name: "Create /var mountable, snapshottable stand-alone datasets"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/var/{{ item.path }}"
    extra_zfs_properties:
      mountpoint: "/var/{{ item.path }}"
      acltype: "{{ item.acl | default(omit) }}"
    state: present
  loop:
    - path: "lib/systemd/coredump"
    - path: "log"
    - path: "log/journal"
      acl: "posixacl"

