- name: "Create /var system datasets that are part of boot environment"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/var{{ itemj.path }}"
    extra_zfs_properties:
      canmount: "off"
      mountpoint: "/var{{ itemj.path }}"
    state: present
  loop:
    - path: ""
    - path: "/lib"
    - path: "/lib/systemd"
  loop_control:
    loop_var: itemj

- name: "Create /var mountable, snapshottable stand-alone datasets"
  zfs:
    name: "{{ dataset_creation_def_zpool_name }}/var/{{ itemj.path }}"
    extra_zfs_properties:
      mountpoint: "/var/{{ itemj.path }}"
      acltype: "{{ itemj.acl | default(omit) }}"
    state: present
  loop:
    - path: "lib/systemd/coredump"
    - path: "log"
    - path: "log/journal"
      acl: "posixacl"
  loop_control:
    loop_var: itemj

