- name: "Add archzfs repo key and sign it"
  block:
    - name: "Import the archzfs-repo-key to the new machine pacman keyring"
      command: pacman-key --recv-keys
                          --config {{ pacman_conf_file|quote }}
                          --gpgdir {{ pacman_keyring_dir|quote }}
                          {{ arch_install_def_archzfs_repo_key|quote }}
    - name: "Sign the imported archzfs-repo-key"
      command: pacman-key --lsign-key
                          --config {{ pacman_conf_file|quote }}
                          --gpgdir {{ pacman_keyring_dir|quote }}
                          {{ arch_install_def_archzfs_repo_key|quote }}
  vars:
    pacman_conf_file: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    pacman_keyring_dir: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/gnupg"

- name: "Refresh chroot pacman database"
  pacman:
    update_cache: yes
    update_cache_extra_args: >-
      --root "{{ arch_install_def_arch_chroot_dir }}"
      --config "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
      --cachedir "{{ arch_install_def_arch_chroot_dir }}/var/cache/pacman/pkg"
      --gpgdir "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/gnupg"
      --hookdir "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/hooks"
      --logfile "{{ arch_install_def_arch_chroot_dir }}/var/log/pacman.log"

- name: "Add 'archzfs-kernels' repo as first-priority repo in pacman.conf"
  blockinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    insertbefore: '^\[core\]$'
    block: |+
      [archzfs-kernels]
      Server = http://end.re/$repo
    state: present

- name: "Add 'archzfs' repo as last-priority repo in pacman.conf"
  blockinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    insertafter: EOF
    block: |+
      [archzfs]
      Server = http://archzfs.com/$repo/x86_64
    state: present

# - name: "Add 'archzfs-kernels' repo to chroot pacman.conf AGAIN....."
#   lineinfile:
#     path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
#     line: "[archzfs-kernels]\nServer = http://end.re/$repo\n"
#     insertbefore: "^\[core\]$"
#     state: present

# - name: "Install 'zfs-linux' and 'zfs-linux-lts' packages to chroot"
#   pacman:
#     name:
#       - "archzfs-linux"
#       - "archzfs-linux-lts"
#     extra_args: >-
#       --root "{{ arch_install_def_arch_chroot_dir }}"
#       --config "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
#       --cachedir "{{ arch_install_def_arch_chroot_dir }}/var/cache/pacman/pkg"
#       --gpgdir "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/gnupg"
#       --hookdir "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/hooks"
#       --logfile "{{ arch_install_def_arch_chroot_dir }}/var/log/pacman.log"

