- name: "Import the archzfs-repo-key to the new machine pacman keyring"
  block:
    - name: "Import the archzfs-repo-key from the Arch Linux keyserver"
      command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                           pacman-key --recv-keys {{ arch_install_def_archzfs_repo_key|quote }}
  rescue:
    - name: "Import key from the Ubuntu keyserver, if Arch keyserver is down"
      command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                           pacman-key --keyserver hkp://keyserver.ubuntu.com
                                      --recv-keys {{ arch_install_def_archzfs_repo_key|quote }}

- name: "Sign the imported archzfs-repo-key"
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       pacman-key --lsign-key {{ arch_install_def_archzfs_repo_key|quote }}

- name: "Add 'archzfs-kernels' repo as first-priority repo in pacman.conf"
  blockinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    insertbefore: '^\[core\]$'
    block: |
      [archzfs-kernels]
      Server = http://end.re/$repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK: archzfs-kernels"
    state: present

- name: "Add 'archzfs' repo as last-priority repo in pacman.conf"
  blockinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    insertafter: EOF
    block: |
      [archzfs]
      Server = http://archzfs.com/$repo/x86_64
    marker: "# {mark} ANSIBLE MANAGED BLOCK: archzfs"
    state: present

- name: "Refresh the pacman database"
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -Syy

- name: "Install 'zfs-linux' and 'zfs-linux-lts' kernel packages to chroot"
  # note: installing kernels will trigger initramfs generation via pacman hook
  # note: initramfs will be rebuilt below, but this cmd creates mkinitcpio.conf
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -S archzfs-linux archzfs-linux-lts

- name: "Configure 'mkinitcpio.conf', for correct zfs initramfs generation"
  lineinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/mkinitcpio.conf"
    regexp: '^HOOKS='
    line: "HOOKS=(base udev autodetect modconf block keyboard zfs usr filesystems shutdown)"
    state: present

- name: "Regenerate initramfs images, using the new settings in mkinitcpio.conf"
  # -P: create norm/fallback images for all kernels (zfs-linux, zfs-linux-lts)
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       mkinitcpio -P

