- name: "Add archzfs repo key and sign it"
  block:
    - name: "Import the archzfs-repo-key to the new machine pacman keyring"
      command: pacman-key --recv-keys
                          --config {{ pacman_conf_file|quote }}
                          --gpgdir {{ pacman_keyring_dir|quote }}
                          {{ arch_install_def_archzfs_repo_key|quote }}
    - name: "Sign the imported archzfs-repo-key"
      command: pacman-key --lsign-key
                          --config {{ pacman_conf_file|quote }}
                          --gpgdir {{ pacman_keyring_dir|quote }}
                          {{ arch_install_def_archzfs_repo_key|quote }}
  vars:
    pacman_conf_file: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    pacman_keyring_dir: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/gnupg"

- name: "Add 'archzfs-kernels' repo as first-priority repo in pacman.conf"
  blockinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    insertbefore: '^\[core\]$'
    block: |
      [archzfs-kernels]
      Server = http://end.re/$repo
    marker: "# {mark} ANSIBLE MANAGED BLOCK: archzfs-kernels"
    state: present

- name: "Add 'archzfs' repo as last-priority repo in pacman.conf"
  blockinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
    insertafter: EOF
    block: |
      [archzfs]
      Server = http://archzfs.com/$repo/x86_64
    marker: "# {mark} ANSIBLE MANAGED BLOCK: archzfs"
    state: present

# - name: "Refresh pacman db, and install 'zfs-linux' and 'zfs-linux-lts' packages"
#   block:
#     - name: "Refresh the pacman database"
#       pacman:
#         update_cache: yes
#         update_cache_extra_args: "{{ pacman_args }}"
#         force: yes
#     - name: "Install 'zfs-linux' and 'zfs-linux-lts' packages to chroot"
#       pacman:
#         name:
#           - "archzfs-linux"
#           - "archzfs-linux-lts"
#         extra_args: "{{ pacman_args }}"
#   vars:
#     pacman_args: >-
#       --root "{{ arch_install_def_arch_chroot_dir }}"
#       --dbpath "{{ arch_install_def_arch_chroot_dir }}/var/lib/pacman"
#       --config "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.conf"
#       --cachedir "{{ arch_install_def_arch_chroot_dir }}/var/cache/pacman/pkg"
#       --gpgdir "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/gnupg"
#       --hookdir "{{ arch_install_def_arch_chroot_dir }}/etc/pacman.d/hooks"
#       --logfile "{{ arch_install_def_arch_chroot_dir }}/var/log/pacman.log"

- name: "Refresh the pacman database"
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -Syy

- name: "Install 'zfs-linux' and 'zfs-linux-lts' packages to chroot"
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -S archzfs-linux archzfs-linux-lts

