- name: "Create the /etc directory, if it does not exist"
  file:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc"
    state: directory

- name: "Generate the /etc/fstab content"
  # -p: exclude pseudofs mounts (the default behavior)
  # -t LABEL: use filesystem-labels as the source IDs in fstab
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       genfstab -p -t LABEL

