- name: "Create the /etc directory, if it does not exist"
  file:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc"
    state: directory

- name: "Generate the /etc/fstab content"
  # -p: exclude pseudofs mounts (the default behavior)
  # -t LABEL: use filesystem-labels as the source IDs in fstab
  command: genfstab -p
                    -t LABEL
                    {{ arch_install_def_arch_chroot_dir|quote }}
  register: genfstab_out

- name: "Put the /etc/fstab content into the new machine /etc/fstab"
  copy:
    content: "{{ genfstab_out.stdout }}\n\n"
    dest: "{{ arch_install_def_arch_chroot_dir }}/etc/fstab"

- name: "Remove 'legacy' zfs entries from /etc/fstab"
  lineinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/fstab"
    regexp: '\bzfs\b'
    state: absent

- name: "Remove blank lines from /etc/fstab"
  lineinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/fstab"
    regexp: '^$'
    state: absent

