- name: "Create EFI ESP (extended sys partition) filesystem(s), and mount"
  include_tasks: mount_esp.yml
  # when: arch_install_def_motherboard_type == "uefi"
  when: arch_install_def_motherboard_type == "bios"

- name: "Generate /etc/fstab file, based on current archiso mounts"
  include_tasks: gen_fstab.yml

- name: "Run 'pacstrap' cmd to install base system (without kernels or initramfs)"
  command: pacstrap {{ arch_install_def_arch_chroot_dir|quote }}
                    base base-devel

- name: "Set the hardware clock, system clock, and time zone"
  include_tasks: set_time.yml

- name: "Set the locale"
  include_tasks: set_locale.yml

- name: "Set the keyboard layout"
  include_tasks: set_keyb_layout.yml

- name: "Set the hostname, and create /etc/hosts routing entries"
  include_tasks: set_hostname.yml

# - name: "Add archzfs repo keys, configure 'pacman.conf', install archzfs kernels"
#   include_tasks: add_archzfs.yml

- name: "Set the system root password, via user input"
  block:
    - name: "Get the new root password from user input"
      pause:
        prompt: "Enter the root password for the new machine:"
        echo: no
        register: password_input
    - name: "Change the root password"
      command:
        cmd: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                        chpasswd
        stdin: "root:{{ password_input.user_input }}"
  # vars_prompt:
  #   - name: input_root_passwd
  #     prompt: "Enter the new system root password"
  #     private: yes
  #     confirm: yes
  # shell: passwd --root {{ arch_install_def_arch_chroot_dir|quote }} root

