- name: "Create EFI partition filesystem(s), and mount"
  block:
    - name: "FAT32-format EFI boot partitions, with identical filesystem labels"
      filesystem:
        fstype: vfat
        dev: "/dev/{{ item_main }}1"
        force: yes
        opts: "-F32 -n {{ efi_fs_label }}"
      loop: "{{ arch_install_def_install_devices }}"
      loop_control:
        loop_var: item_main
    - name: "Create '/efi' directory for mounting EFI boot partition"
      file:
        path: "{{ efi_dir }}"
        state: directory
    - name: "Unmount EFI boot partition from '[chroot]/efi', if it is mounted"
      command: umount {{ archiso_config_def_arch_chroot }}/efi
    - name: "Mount EFI boot partition to '/efi' (random boot part, if mirrored)"
      command:
        cmd: mount --label {{ efi_fs_label|quote }}
                   --target {{ efi_dir|quote }}
        warn: false
  vars:
    efi_dir: "{{ arch_install_def_arch_chroot }}/efi"
    efi_fs_label: "EFIFS"
  # when: arch_install_def_motherboard_type == "uefi"
  when: arch_install_def_motherboard_type == "bios"

# - name: "Run 'pacstrap' cmd to install base system to installation disk(s)"
#   command: pacstrap /mnt base base-devel

