- name: "Create EFI partition filesystem(s), and mount"
  block:
    - name: "FAT32-format EFI boot partitions, with identical filesystem labels"
      filesystem:
        fstype: vfat
        dev: "/dev/{{ item_main }}1"
        force: yes
        opts: "-F32 -n {{ arch_install_def_efi_fs_label }}"
      loop: "{{ arch_install_def_install_devices }}"
      loop_control:
        loop_var: item_main
    - name: "Create '/efi' directory for mounting EFI boot partition"
      file:
        path: "{{ arch_install_def_efi_chroot_dir }}"
        state: directory
    - name: "Mount EFI boot partition to '/efi' (random boot part, if mirrored)"
      command:
        cmd: mount --label {{ arch_install_def_efi_fs_label|quote }}
                   --target {{ arch_install_def_efi_chroot_dir|quote }}
        warn: false
  # when: arch_install_def_motherboard_type == "uefi"
  when: arch_install_def_motherboard_type == "bios"

- name: "Generate the new-machine /etc/fstab, based on current archiso mounts"
  # -p: exclude pseudofs mounts (the default behavior)
  # -t LABEL: use filesystem-labels as the source IDs in fstab
  command: genfstab -p
                    -t LABEL
                    {{ arch_install_def_arch_chroot_dir|quote }}
                    >> {{ arch_install_def_arch_chroot_dir|quote }}/etc/fstab

# - name: "Run 'pacstrap' cmd to install base system to installation disk(s)"
#   command: pacstrap /mnt base base-devel

