- name: "Create EFI ESP (extended sys partition) filesystem(s), and mount"
  include_tasks: mount_esp.yml
  # when: arch_install_def_motherboard_type == "uefi"
  when: arch_install_def_motherboard_type == "bios"

- name: "Generate /etc/fstab file, based on current archiso mounts"
  include_tasks: gen_fstab.yml
  vars:
    chroot_etc_dir: "{{ arch_install_def_arch_chroot_dir }}/etc"

- name: "Run 'pacstrap' cmd to install base system to installation disk(s)"
  command: pacstrap {{ arch_install_def_arch_chroot_dir|quote }}
                    base base-devel

- name: "Set the hardware clock, system clock, and time zone"
  include_tasks: set_time.yml

- name: "Set the locale"
  include_tasks: set_locale.yml

