- name: "Configure /etc/locale.gen, by setting locale/charset in last line"
  lineinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/locale.gen"
    line: "{{ arch_install_def_locale }} UTF-8"
    insertafter: EOF
    state: present

- name: "Use /etc/locale.gen to generate the locale-archive"
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       locale-gen

- name: "Set LANG environment var in 'locale.conf' to the specified locale"
  lineinfile:
    path: "{{ arch_install_def_arch_chroot_dir }}/etc/locale.conf"
    line: "LANG={{ arch_install_def_locale }}"
    insertafter: EOF
    state: present
    create: yes

