- name: "Install 'networkmanager' package to chroot"
  command: arch-chroot {{ arch_install_def_arch_chroot_dir|quote }}
                       pacman --noconfirm -S networkmanager

- name: "Enable systemd NetworkManager service"
  command: systemctl --root={{ arch_install_def_arch_chroot_dir|quote }}
                     enable NetworkManager.service

